# Airbnb Trends

There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
# Reading the review.tsv file
airbnb = pd.read_csv('./airbnb_last_review.tsv', sep='\t')
airbnb['last_review'] = pd.to_datetime(airbnb['last_review'], format='%B %d %Y', dayfirst=True)
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 591.0+ KB

In [28]:
airbnb.head()

   listing_id    host_name last_review
0        2595     Jennifer  2019-05-21
1        3831  LisaRoxanne  2019-07-05
2        5099        Chris  2019-06-22
3        5178     Shunichi  2019-06-24
4        5238          Ben  2019-06-09

Q: What are the dates of the earliest and most recent reviews?<br> 
Store these values as two separate variables with your preferred names.

In [41]:
# Fetch most recent review - using max method
print(airbnb['last_review'].max())
# Achieiving same result using iloc
print(airbnb['last_review'].sort_values(ascending=False).iloc[0])

2019-07-09 00:00:00
2019-07-09 00:00:00

In [42]:
# Fetch earliest review - using min method
print(airbnb['last_review'].min())
# Achieiving same result using iloc
print(airbnb['last_review'].sort_values(ascending=False).iloc[-1])

2019-01-01 00:00:00
2019-01-01 00:00:00

In [49]:
# verifying the result
pd.read_csv('./airbnb_last_review.tsv', sep='\t', parse_dates=["last_review"], date_format='%B %d %Y').sort_values("last_review", ascending=True)

       listing_id      host_name last_review
12007    21751907  Aura Angelica  2019-01-01
10430    19708955          Karen  2019-01-01
14845    25931882            Can  2019-01-01
7203     13936825        Shlomit  2019-01-01
17123    28813184        Carolyn  2019-01-01
...           ...            ...         ...
23952    34933891        Jessica  2019-07-08
9595     18331097   Jimmy &Cindy  2019-07-08
9505     18173787       Danielle  2019-07-08
17563    29256134          Scott  2019-07-08
58          18152       Victoria  2019-07-09

[25209 rows x 3 columns]